Fix issues with sidebar
Appsilon/semantic.dashboard pull request #154
Opened 2021-01-07 13:48 UTC by drzamich

Closes #144 
# Fix issues with sidebar and scrolls.

## Before
### Sidebar on the left
![sidebar_left_before](https://user-images.githubusercontent.com/26330688/103899739-1dadb680-50f7-11eb-858a-826fc77b5f22.gif)
### Sidebar on top
![sidebar_top_before](https://user-images.githubusercontent.com/26330688/103899779-2d2cff80-50f7-11eb-8c0e-e315bf368e0a.gif)

## After
### Sidebar on the left
![sidebar_left_after](https://user-images.githubusercontent.com/26330688/103899813-3ae28500-50f7-11eb-9171-6219cd19de02.gif)
### Sidebar on top
![sidebar_top_after](https://user-images.githubusercontent.com/26330688/103899820-3fa73900-50f7-11eb-9fcc-f498a7b2543d.gif)

Short description (with a reference to an issue).

2021-01-14 10:14 UTC, dokato requested changes
🥳 Wow, impressive work! This really moves `semantic.dashboard` forward. A bunch of minor comments from me below.

2021-01-14 10:14 UTC, dokato commented on examples/minimal/app_custom_classes.R
> +  class = "stronka",
can you replace this class by `my_page`

2021-01-14 10:14 UTC, dokato commented on examples/minimal/app_custom_classes.R
> +  sidebar_body_class = "sidebar_and_bodyyy",
`sidebar_and_bodyyy` -> `my_sidebar_and_body`

2021-01-14 10:14 UTC, dokato commented on examples/minimal/app_custom_classes.R
> +    class="sidebarek",
`sidebarek` -> `my_sidebar`

BTW what is difference between: `sidebar_body_class` and class within `dashboardSidebar`?

2021-01-14 10:14 UTC, dokato commented on examples/minimal/app_custom_classes.R
> +    class="cialko")
`cialko` -> `my_body`

2021-01-14 10:14 UTC, dokato commented on examples/minimal/app_header_elements.R
> +server <- function(input, output) {
I really like this example. Is it possible to set side margins (of left, center, right) to some small value (e.g. 1%) such that they do not stick to the borders of sidebar menu
<img width="297" alt="Screenshot 2021-01-14 at 10 00 15" src="https://user-images.githubusercontent.com/4547289/104576195-c906c000-564f-11eb-8a72-ce1bf6b81d51.png">

2021-01-14 11:59 UTC, dokato requested changes
Please make sure that the example from README renders the same as in `inst/compare.png`

2021-01-14 14:14 UTC, drzamich commented on examples/minimal/app_custom_classes.R
> +    class="sidebarek",
`sidebar_body_class` is applied to a `<div>` that contains both `dashboardSidebar` and `dashboardBody`. I will rename this parameter to `sidebar_and_body_container_class` to make it more clear.
![image](https://user-images.githubusercontent.com/26330688/104601964-2b28ea80-567b-11eb-83cb-bd13a2dbdd5c.png)

2021-01-14 15:16 UTC, drzamich commented on examples/minimal/app_header_elements.R
> +server <- function(input, output) {
It is possible but I'm not sure if we want to do this, here's why:

1. Putting text as `left` or `right` is just one of many possibilities. I imagine a case when a user would like to put there another button, then they would have to explicitly remove the margins.
2. In order to achieve that we would have to wrap elements in more `<div>`s and complicate the structure of the DOM as well the code even more, I am not sure if it's worth it.

My solution is that I modify the example to showcase how easy it is to add margin when we want it. 
![image](https://user-images.githubusercontent.com/26330688/104609853-c3c36880-5683-11eb-8ed1-fdb052cc0d09.png)

What do you think about that?

2021-01-14 16:06 UTC, dokato commented on examples/minimal/app_header_elements.R
> +server <- function(input, output) {
Sure that's fine, let's update example!

2021-01-14 16:16 UTC, drzamich commented on examples/minimal/app_header_elements.R
> +server <- function(input, output) {
Example updated :)

2021-01-15 11:38 UTC, dokato approved these changes
LGTM, Excellent work @drzamich !

2021-01-15 11:38 UTC, merged