Add sidebarUserPanel
Appsilon/semantic.dashboard pull request #198
Opened 2023-01-27 20:59 UTC by averissimo

# Implements shinydashboard function `sidebarUserPanel`

- 182

What was changed:

- [x] Style the margins of the element
- [x] Adds documentation
- [x] Removes `sidebarUserPanel` from `not_implemented` list in tests
- [x] Regenerate documentation (man & NAMESPACE

## Open questions

- is there a better way to generate padding values? 

Values `padding: .92857143em 1.14285714em;` are taken from Semantic UI and they'll translate to `16px`

- in `R/semantic_dashboard.R` there is a different implementation of `dashboard_sidebar` line 199.

This WIP had a call via `do.call` that avoided using `..1[-1]`, but the implementation on the `develop` branch is newer. I kept that one for now.

## Example

![image](https://user-images.githubusercontent.com/211358/215196244-0d614f55-3ece-405a-a866-6451d56562bf.png)

2023-02-03 14:01 UTC, osenan requested changes
Hi, good job! It looks very good

Let me answer some of your questions: The change in the `dashboard_sidebar` using `do.call` is needed to correctly add more elements as html and not as a list. I agree of keeping this approach. Indeed it will benefit the usability of the sidebar in general.

Regarding the padding of the sidebar user panel, I think that it will be easier to maintain to use `px` instead of `em` as suggested in my comment. If user needs to change font size by css then they can also change the padding of the sidebar user panel if it does not look good.

Please change the padding and answer my comment regarding the `renv` I think we do not need it.

Finally, can you confirm that the image we upload is a free image?

2023-02-03 14:01 UTC, osenan commented on .Rbuildignore
> +^renv$
why do we need `renv` folder and `renv.lock` file here?

2023-02-03 14:01 UTC, osenan commented on inst/semantic.dashboard.css
> +  padding: .92857143em 1.14285714em;
As you put in the description, using `em` looks like a magic number. I think we can have similar effect by using `padding: 10px 10px;` which looks more easy to understand

2023-02-03 14:04 UTC, osenan commented on styles/layout/_sidebar.scss
> +  padding: .92857143em 1.14285714em;
same thing than in the `css` file, better use `px` can be set to 10

2023-03-17 16:11 UTC, averissimo commented on .Rbuildignore
> +^renv$
You're right, it sneaked in here. Sorry!

2023-03-17 16:42 UTC, averissimo commented on inst/semantic.dashboard.css
> +  padding: .92857143em 1.14285714em;
Done!

2023-03-17 16:42 UTC, averissimo commented on styles/layout/_sidebar.scss
> +  padding: .92857143em 1.14285714em;
Done!

2023-03-17 16:48 UTC, averissimo commented
@osenan Sorry for taking this long to reply to the review.

I think I resolved all your pending comments:

* The `renv` sneaks in a lot when using it locally to manage versions.
* Change the em to px
    * Updated SASS call to reflect current library calls

Regarding the image, it has a Free to Use license 

Photo from: https://www.pexels.com/photo/silhouette-of-person-standing-on-beach-during-sunset-3492736/

https://www.pexels.com/license/

![image](https://user-images.githubusercontent.com/211358/225967207-d921ff2d-206f-4edf-a440-0ac70fe06f76.png)

2023-03-24 18:38 UTC, osenan approved these changes
Great! And thank you for explanation

2023-03-24 18:38 UTC, merged